### ISSUE TITLE
fail to import brightway 

### ISSUE THREAD

**Issue by mfastudillo** [brightway-lca/brightway2-calc#36]
Hello, I have recently re-installed brightway and I get an error when I trying to import bw2calc (v1.8.0) on a windows machine. It seems to be due to library used by the solver Pardiso (v 0.2.2 installed) ... I am not sure how to address this.  

```python
 FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-a3ddbb8a34e8> in <module>
----> 1 import brightway2 as bw

~\Anaconda3\envs\bw\lib\site-packages\brightway2\__init__.py in <module>
      1 # -*- coding: utf-8 -*
      2 from bw2data import *
----> 3 from bw2calc import *
      4 from bw2io import *
      5

~\Anaconda3\envs\bw\lib\site-packages\bw2calc\__init__.py in <module>
     24 __version__ = (1, 8, 0)
     25
---> 26 from .lca import LCA
     27 from .dense_lca import DenseLCA
     28 from .independent_lca import IndependentLCAMixin

~\Anaconda3\envs\bw\lib\site-packages\bw2calc\lca.py in <module>
     27
     28 try:
---> 29     from pypardiso import factorized, spsolve
     30 except ImportError:
     31     from scipy.sparse.linalg import factorized, spsolve

~\Anaconda3\envs\bw\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\Anaconda3\envs\bw\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\Anaconda3\envs\bw\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\Anaconda3\envs\bw\lib\importlib\_bootstrap.py in _load_backward_compatible(spec)

<frozen zipimport> in load_module(self, fullname)

~\Anaconda3\envs\bw\lib\site-packages\pypardiso-0.2.2-py3.6.egg\pypardiso\__init__.py in <module>
      2
      3 from .pardiso_wrapper import PyPardisoSolver
----> 4 from .scipy_aliases import spsolve, factorized
      5 from .scipy_aliases import pypardiso_solver as ps
      6

~\Anaconda3\envs\bw\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\Anaconda3\envs\bw\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\Anaconda3\envs\bw\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\Anaconda3\envs\bw\lib\importlib\_bootstrap.py in _load_backward_compatible(spec)

<frozen zipimport> in load_module(self, fullname)

~\Anaconda3\envs\bw\lib\site-packages\pypardiso-0.2.2-py3.6.egg\pypardiso\scipy_aliases.py in <module>
      7 # pypardsio_solver is used for the 'spsolve' and 'factorized' functions. Python crashes on windows if multiple
      8 # instances of PyPardisoSolver make calls to the Pardiso library
----> 9 pypardiso_solver = PyPardisoSolver()
     10
     11

~\Anaconda3\envs\bw\lib\site-packages\pypardiso-0.2.2-py3.6.egg\pypardiso\pardiso_wrapper.py in __init__(self, mtype, phase, size_limit_storage)
     64             self.libmkl = ctypes.CDLL('libmkl_rt.dylib')
     65         elif sys.platform == 'win32':
---> 66             self.libmkl = ctypes.CDLL('mkl_rt.dll')
     67         else:
     68             self.libmkl = ctypes.CDLL('libmkl_rt.so')

~\Anaconda3\envs\bw\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    379
    380         if handle is None:
--> 381             self._handle = _dlopen(self._name, mode)
    382         else:
    383             self._handle = handle

FileNotFoundError: Could not find module 'mkl_rt.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by BenPortner** [comment]
Tried installing brightway into a new environment today and getting the same error. This is the command I used:
`conda create -n BW2 -y -c conda-forge -c cmutel -c haasad brightway2 jupyter`

My machine runs Microsoft Windows [Version 10.0.19043.985].

**Comment by m-y-reich** [comment]
I had the same/similar issue after the last update. 
I first tried to reinstall pyparadisio because it flagged an error there in my case but this did not resolve it. 
What die resolve it was to simply remove and reinstall brightway (in the same environment, but setting up a new one should probably work equally fine).

**Comment by BenPortner** [comment]
@m-y-reich What are the commands you used for deinstalling and reinstalling brightway?

**Comment by m-y-reich** [comment]
> 
> 
> @m-y-reich What are the commands you used for deinstalling and reinstalling brightway?

in the respective environment I simply entered 
`conda remove brightway2`
(see [https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html))

and then I reinstalled it with the installation-command from the the [brightway installation guide](https://2.docs.brightway.dev/installation.html) 
`conda install -y -q -c conda-forge -c cmutel -c haasad brightway2 jupyter`

**Comment by haasad** [comment]
@cmutel, please let me know if you need any input/changes from my side. I know I haven't contributed to brightway in quite some time, but I feel responsible for pypardiso

**Comment by BenPortner** [comment]
@m-y-reich the problem persists. Can you redo the procedure on your computer in a new environment to see if it still works?

**Comment by cmutel** [comment]
@BenPortner @haasad I am trying to rebuild this using the conda-forge, which will produce specific versions for each OS and Py version (https://github.com/cmutel/PyPardisoProject). At some point I would also like to extend PyPardiso to support the newer versions which are supposed to be [much faster](https://www.pardiso-project.org/).

@haasad I would love to chat, please get in touch :)

**Comment by cmutel** [comment]
I think [this](https://github.com/conda-forge/staged-recipes/pull/15106) might help. Will take a day or two to get integrated into the `conda-forge` pipeline.

**Comment by haasad** [comment]
FYI: the complex matrices weren't merged to pypardiso since the author of the PR found errors, see https://github.com/haasad/PyPardisoProject/pull/9. I'd be careful to put this on conda-forge without further testing

**Comment by cmutel** [comment]
@haasad @BenPortner Using conda-forge packaging [didn't help](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=331362&view=logs&jobId=240f1fee-52bc-5498-a14a-8361bde76ba0&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77) - same error. 

The [line loading the problematic linked library](https://github.com/haasad/PyPardisoProject/blob/master/pypardiso/pardiso_wrapper.py#L66) is innocuous:

```python
self.libmkl = ctypes.CDLL('mkl_rt.dll')
```

This worked just fine for years, until it didn't. Something changed in the way MKL was packaged, and this isn't something that we have a lot of control over.

Here are some possible answers:

* Install an [older version of MKL](https://anaconda.org/conda-forge/mkl/files).
* Set an [environment variable](https://stackoverflow.com/a/66775448/164864) to change how [Conda searches for libraries](https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed).
* [Installing Cython?](https://stackoverflow.com/a/63559749/164864)

In the longer term, someone with a Win10 computer needs to install MKL in a clean environment, and find out why it isn't on the path. If it helps, we aren't the only ones struggling with this...

**Comment by haasad** [comment]
I opened https://github.com/haasad/PyPardisoProject/issues/12

I did some tests on windows, it seems the new mkl [2021.2.0](https://anaconda.org/conda-forge/mkl) from conda-forge breaks something with the path discovery on windows. [mkl 2020.2](https://anaconda.org/anaconda/mkl) from the `defaults` channel still worked in my tests.

As a quick fix you can create a new environment like this:
```
conda create -n bw38 -c conda-forge -c cmutel -c haasad brightway2 mkl=2020.2 python=3.8
```
I would be grateful if you could test this @BenPortner, @m-y-reich.

I'll look for a permanent fix asap.

**Comment by StpdFox** [comment]
There's a workaround. You have to create a new enviroment with this command :
`conda create -n <Your Environment Name> -c conda-forge -c cmutel -c bsteubing -c haasad -c pascallesage  "activity-browser>2.4" mkl=2020.2 python=3.8`

Then activate that environment by typing 
`conda activate <Your Environment Name>`

and run the AB by typing 
`activity-browser`

i hope this works for you.

**Comment by BenPortner** [comment]
> As a quick fix you can create a new environment like this:
> 
> ```
> conda create -n bw38 -c conda-forge -c cmutel -c haasad brightway2 mkl=2020.2 python=3.8
> ```

Work's like a charm.

**Comment by cmutel** [comment]
I was finally able to get a [working recipe for conda-forge](https://github.com/conda-forge/staged-recipes/pull/15106), so this problem should go away soon!

**Comment by romainsacchi** [comment]
It is looking for "mkl_rt.dll" while the DLL file is now named "mkl_rt.1.dll" for some reason unknown to me.
![image](https://user-images.githubusercontent.com/22473067/120624017-8ad43680-c460-11eb-9ee6-002e0b9d031c.png)

**Comment by haasad** [comment]
After fiddling with the anaconda client for way too long (it's broken on 3.9 and fails silently) I released v0.3.0 of pypardiso which contains a fix for this issue.

Updating pypardiso will resolve the problems on windows and new environments should work again:
```
conda update -c haasad pypardiso
```
@cmutel, I'll prepare a PR for the conda-forge recipe

**Comment by cmutel** [comment]
@haasad [Already done](https://github.com/conda-forge/staged-recipes/pull/15106/commits/cba74d781c04f862057d2431ccd937287589cf46). Please let me know if you want to take over or be listed as a maintainer.

**Comment by haasad** [comment]
Great! I'd appreciate if you add me as a maintainer :+1:

**Comment by cmutel** [comment]
@haasad OK, you need to comment in the linked PR to show you are OK being listed as such.

**Comment by Haniezarafshani** [comment]
> > @m-y-reich What are the commands you used for deinstalling and reinstalling brightway?
> 
> in the respective environment I simply entered `conda remove brightway2` (see https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html)
> 
> and then I reinstalled it with the installation-command from the the [brightway installation guide](https://2.docs.brightway.dev/installation.html) `conda install -y -q -c conda-forge -c cmutel -c haasad brightway2 jupyter`

@haasad Hi! I reinstall and install it again but unfortunately, I still have this error:
I really appreciate your help

Traceback (most recent call last):
  File "C:/Users/u0135744a/PycharmProjects/10.01.2022/import ecoinvent.py", line 1, in <module>
    import brightway2
  File "C:\ProgramData\Anaconda3\envs\brightway2\lib\site-packages\brightway2\__init__.py", line 2, in <module>
    from bw2data import *
  File "C:\ProgramData\Anaconda3\envs\brightway2\lib\site-packages\bw2data\__init__.py", line 35, in <module>
    from .meta import (
  File "C:\ProgramData\Anaconda3\envs\brightway2\lib\site-packages\bw2data\meta.py", line 186, in <module>
    geomapping = GeoMapping()
  File "C:\ProgramData\Anaconda3\envs\brightway2\lib\site-packages\bw2data\meta.py", line 66, in __init__
    super(GeoMapping, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\brightway2\lib\site-packages\bw2data\serialization.py", line 122, in __init__
    self.load()
  File "C:\ProgramData\Anaconda3\envs\brightway2\lib\site-packages\bw2data\serialization.py", line 127, in load
    self.data = self.deserialize()
  File "C:\ProgramData\Anaconda3\envs\brightway2\lib\site-packages\bw2data\serialization.py", line 240, in deserialize
    return self.unpack(pickle.load(open(self.filepath, "rb")))
ValueError: unsupported pickle protocol: 5

**Comment by haasad** [comment]
@Haniezarafshani  As far as I know this is an error that shouldn't happen unless you use an older python version (below 3.8). You can check which version you're using by running:
```python --version``` or ```conda list```

I suggest to use the same environment that you created [earlier for the activity-browser](https://github.com/LCA-ActivityBrowser/activity-browser/issues/694#issuecomment-1015240662) to run your brightway code. Otherwise you can also create a new separate environment for brightway. Something like this:
```
conda create -n bw_new -c conda-forge -c cmutel brightway2 intel-openmp=2021.4 python=3.9
```
I assume you then also have to select the environment in Pycharm.

See also: https://github.com/brightway-lca/brightway2-data/issues/83

**Comment by Haniezarafshani** [comment]
> @Haniezarafshani As far as I know this is an error that shouldn't happen unless you use an older python version (below 3.8). You can check which version you're using by running: `python --version` or `conda list`
> 
> I suggest to use the same environment that you created [earlier for the activity-browser](https://github.com/LCA-ActivityBrowser/activity-browser/issues/694#issuecomment-1015240662) to run your brightway code. Otherwise you can also create a new separate environment for brightway. Something like this:
> 
> ```
> conda create -n bw_new -c conda-forge -c cmutel brightway2 intel-openmp=2021.4 python=3.9
> ```
> 
> I assume you then also have to select the environment in Pycharm.
> 
> See also: [brightway-lca/brightway2-data#83](https://github.com/brightway-lca/brightway2-data/issues/83)

Thank you very much for your quick reply. it was so useful!
 the problem was solved by [ValueError: unsupported pickle protocol: 5 - Numpy 1.13.3 or above is required for this version of scipy (detected version 1.11.3) #73]

**Comment by bthnkrts** [comment]
Hello everyone,

Recently I am struggling with a problem of brightway import. I am performing an LCA project for my master thesis and it is stuck. Since yesterday, python/jupyternotebook is giving the following problem. I need to find a solution asap. Is there anyone who can help me? Any advice or answer would be awesomely helpful.

**FYI: I deleted and re-created brightway2 for my env. Also, I deleted all software and re-installed it as it is recommended previously. Unfortunately, it didn`t work.**

### **INPUT**
import brightway2 as bw
import os               
import numpy as np  
import pandas as pd    
from matplotlib import pyplot as plt

### **OUTPUT**

ImportError                               Traceback (most recent call last)
File ~\anaconda3\envs\MG\lib\site-packages\bw2data\serialization.py:242, in PickledDict.deserialize(self)
    241 try:
--> 242     return self.unpack(pickle.load(open(self.filepath, "rb")))
    243 except ImportError:

File ~\anaconda3\envs\MG\lib\site-packages\bw2data\backends\__init__.py:5, in <module>
      3 from eight import *
----> 5 from .base import LCIBackend
      6 from .peewee import SQLiteBackend

File ~\anaconda3\envs\MG\lib\site-packages\bw2data\backends\base.py:5, in <module>
      3 from eight import *
----> 5 from .. import (
      6     config,
      7     databases,
      8     geomapping,
      9     mapping,
     10     projects,
     11 )
     12 from ..data_store import ProcessedDataStore

ImportError: cannot import name 'databases' from partially initialized module 'bw2data' (most likely due to a circular import) (C:\Users\cansu\anaconda3\envs\MG\lib\site-packages\bw2data\__init__.py)

During handling of the above exception, another exception occurred:

PickleError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import brightway2 as bw
      2 import os               # to use "operating system dependent functionality"
      3 import numpy as np      # "the fundamental package for scientific computing with Python"

File ~\anaconda3\envs\MG\lib\site-packages\brightway2\__init__.py:2, in <module>
      1 # -*- coding: utf-8 -*
----> 2 from bw2data import *
      3 from bw2calc import *
      4 from bw2io import *

File ~\anaconda3\envs\MG\lib\site-packages\bw2data\__init__.py:35, in <module>
     33 from .project import projects
     34 from .utils import set_data_dir
---> 35 from .meta import (
     36     dynamic_calculation_setups,
     37     calculation_setups,
     38     databases,
     39     geomapping,
     40     mapping,
     41     methods,
     42     normalizations,
     43     preferences,
     44     weightings,
     45 )
     47 # Add metadata class instances to global list of serialized metadata
     48 config.metadata.extend([
     49     dynamic_calculation_setups,
     50     calculation_setups,
   (...)
     57     weightings,
     58 ])

File ~\anaconda3\envs\MG\lib\site-packages\bw2data\meta.py:192, in <module>
    190 preferences = Preferences()
    191 weightings = WeightingMeta()
--> 192 calculation_setups = CalculationSetups()
    193 dynamic_calculation_setups = DynamicCalculationSetups()

File ~\anaconda3\envs\MG\lib\site-packages\bw2data\serialization.py:123, in SerializedDict.__init__(self, dirpath)
    118     raise NotImplemented("SerializedDict must be subclassed, and the filename must be set.")
    119 self.filepath = os.path.join(
    120     dirpath or projects.dir,
    121     self.filename
    122 )
--> 123 self.load()

File ~\anaconda3\envs\MG\lib\site-packages\bw2data\serialization.py:128, in SerializedDict.load(self)
    126 """Load the serialized data. Creates the file if not yet present."""
    127 try:
--> 128     self.data = self.deserialize()
    129 except IOError:
    130     # Create if not present
    131     self.data = {}

File ~\anaconda3\envs\MG\lib\site-packages\bw2data\serialization.py:245, in PickledDict.deserialize(self)
    243 except ImportError:
    244     TEXT = "Pickle deserialization error in file '%s'" % self.filepath
--> 245     raise PickleError(TEXT)

PickleError: Pickle deserialization error in file 'C:\Users\cansu\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682\setups.pickle'

**Comment by morphiumdeus** [comment]
Hi, this morning out of the blue brightway started giving me the same error as @bthnkrts . Did anyone find a solution to this? Thanks!

**Comment by romainsacchi** [comment]
Hi,
go in your folder C:\Users\cansu\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
and
* make a copy of `setups.pickle` (just in case)
* delete `setups.pickle` file (don't worry, it'll be regenerated), 
* and restart your notebook.

**Comment by cmutel** [comment]
@morphiumdeus Does a thumbs up mean that your problem is fixed?

In general, this is a stupid error caused by a mistake on my fault. This is because we saved used `pickle.HIGHEST_PROTOCOL`, and a new, backwards-incompatible, protocol was introduced in 3.8. The problem comes when you have two environments on your computer - the one with Python >= 3.8 will save in the latest protocol, and then the <3.8 environment can't read it and raises an error.

The later releases of Brightway avoid this by forcing protocol `4` (<3.8 compatible) in [the database](https://github.com/brightway-lca/brightway2-data/blob/0276c282806c881850874235c5e4888da9cd7245/bw2data/sqlite.py#L9) and in [separate `pickle` files](https://github.com/brightway-lca/brightway2-data/blob/0276c282806c881850874235c5e4888da9cd7245/bw2data/serialization.py#L222).

**Comment by morphiumdeus** [comment]
Sorry, @cmutel, yes this solves the problem. Thanks for the quick help!

**Comment by joanaalbano** [comment]
Hey there!

I'm a newbie to brightway2, so please forgive any "dumb" questions.

I've been trying to install brightway2 following the [Instructions](https://2.docs.brightway.dev/installation.html) step-by-step, however I've been getting the following error:

![image](https://user-images.githubusercontent.com/122452775/211828599-ce8a7c5c-f2a4-431f-88db-9838d7128c89.png)
![image](https://user-images.githubusercontent.com/122452775/211828641-6c78f0bc-d1d3-4bc7-8ea0-55e9a46c2f4c.png)
![image](https://user-images.githubusercontent.com/122452775/211828771-1d980de8-babd-4ec9-9eab-04da8586d8d3.png)

Could someone help me solve this, please? I've been running in circles here :(

thanks!

**Comment by marc-vdm** [comment]
Welcome to the community! 

This is not your fault, something needs to be updated in Brightway. Something changed in the library `numpy`. You can fix this on your side for now by doing the following in `conda`:

`conda activate bw2` (if you hadn't already activated the environment)
`conda install numpy=1.23.5`

This will install the right version of `numpy`, which will solve your problem until the problem is properly solved in Brightway.

Good luck!

**Comment by BenPortner** [comment]
Hi @joanaalbano,

Thanks for using brightway! Your error and the solution have been described here: https://github.com/brightway-lca/brightway2-data/issues/117. It can be fixed by downgrading numpy to version 1.23.5: `conda install numpy=1.23.5`.

- Ben

**Comment by joanaalbano** [comment]
Hello @marc-vdm and @BenPortner! For some reason, I was getting massive errors when using `conda install numpy=1.23.5`, but it worked when using `pip install --upgrade numpy==1.23.5`. 

Thanks a lot for your help!!
